# configuration for github actions
---
name: checks

#trigger
on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04 # run this action on prebuild os in github.
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v1 # existing action in guthub
        with: 
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
      - name: Lint 
        run: docker-compose run --rm app sh -c "flake8"